
language: java

# We can specify a list of JDKs to be used for testing
# A list of available JDKs in Trusty can be seed in:
# https://docs.travis-ci.com/user/reference/xenial/#jvm-clojure-groovy-java-scala-support
jdk:
 - openjdk8
 - openjdk11
 addons:
   sonarcloud:
     organization: andreadepaolis95
     token: K7_hiLYPZYWrVa9rCQqNtA
     
 
script:
  -ant build 
  -sonar-scanner


  
